### ISSUE TITLE
TypeError when searching for prototype Object method

### ISSUE THREAD

**Issue by adiktofsugar** [micromatch/picomatch#66]
If you search for one of [the protoype Object methods or properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object), it'll throw an error because of an optimization in `parse`:
```
input = REPLACEMENTS[input] || input;
```

Sample code:
```
> const pm = require('picomatch')
> pm('toString')
Thrown:
TypeError: output.startsWith is not a function
    at Object.exports.removePrefix (/path/to/node_modules/picomatch/lib/utils.js:48:14)
    at parse (/path/to/node_modules/picomatch/lib/parse.js:130:17)
    at Function.picomatch.makeRe (/path/to/node_modules/picomatch/lib/picomatch.js:291:14)
    at picomatch (/path/to/node_modules/picomatch/lib/picomatch.js:55:17)
```

**Comment by mrmlnc** [comment]
https://github.com/micromatch/picomatch/pull/144
https://github.com/micromatch/picomatch/releases/tag/4.0.3
